#!/bin/bash

# Этот скрипт создает .env файл с переменными из Vercel
# Запустите его ОДИН РАЗ на сервере, указав значения переменных

cat > .env << 'EOF'
# Supabase Configuration
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}

# PostgreSQL Configuration  
POSTGRES_URL=${POSTGRES_URL}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DATABASE=${POSTGRES_DATABASE}

# Server Configuration
SERVER_HOST=${SERVER_HOST:-0.0.0.0}
SERVER_PORT=${SERVER_PORT:-8000}
FASTAPI_URL=${FASTAPI_URL}

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

# JWT Secret
JWT_SECRET_KEY=${JWT_SECRET_KEY}

# CORS
ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}

# Blob Storage
BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
EOF

echo "✓ Файл .env создан"
